user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}

stream
{
        upstream se1{
                server 127.0.0.1:4455;
        }
        upstream se2{
                server se2:443;
        }
        upstream se3{
                server se3:443;
        }
        upstream se4{
                server se4:443;
        }
        upstream se5{
                server se5:443;
        }
        upstream tk1r{
                server tk1.bitc.eu.org:4455;
        }
        upstream tk2r{
                server tk2.bitc.eu.org:4455;
        }
        upstream xyz{
                server df810594c639v.cloudfront.net:443;
        }
        upstream eu{
                server d1to2me5cb4qc0.cloudfront.net:443;
        }
        upstream ch{
                server d2m1uhh1yoblpo.cloudfront.net:443;
        }
        upstream org{
                server d213ejxlf2llc8.cloudfront.net:443;
        }
        map $ssl_preread_server_name $CJ{
                se1.cnbit.eu.org se1;
                www.lovelyway.cn se2;
                www.rcexl.cn se3;
                aming.ourdisc.net se4;
                loa-todo.com se5;
                www.microsoft.com tk1r;
                www.changeedu.net tk2r;
                anydoor.xyz xyz;
                anydoor.eu.org eu;
                anydoor.cloudns.ch ch;
                anydoor.cloudns.org org;
                default se1;
        }
        server{
                listen 443;
                listen [::]:443;
                ssl_preread on;
                proxy_pass $CJ;
        }
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';


    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
